### ISSUE TITLE
"Through the Jet Stream" naming convention

### ISSUE THREAD

**Issue by onlymx13** [TimeTravelPenguin/SM64TASArchive#1]
I like your naming convention of [star name].m64, but what will happen with "Through the Jet Stream"? Is it all right to leave them both with the same name?

**Comment by TimeTravelPenguin** [comment]
Do you mean in the event of a new improvement? The naming will remain the same, yes. It will have a different sub-folder for time.
`IL/{Level}/{Star}/{Time}/` is the base directory for all IL .m64 and .st files.
