### ISSUE TITLE
U or J ROM Identified in Filename

### ISSUE THREAD

**Issue by MikeXander** [TimeTravelPenguin/SM64TASArchive#3]
There is currently no convention to identify which ROM the files use other than opening it in the emulator to find out.

I'd like to suggest adding a "(U)" or "(J)" to the end of the m64/st filenames

**Comment by TimeTravelPenguin** [comment]
That is a good suggestion. That might be sufficient, yes. This means we need to ensure ALL WR are either U of J, and *NOT* something like the ghost hack, or some other version.

**Comment by TimeTravelPenguin** [comment]
All files have now been named accordingly
